#!/bin/sh

################################################################################
#
# USAGE: /sbin/remapuser USERNAME NEW-UID NEW-GUID comands ....
#
# (*) remaps user USERNAME to given UID/GID
# (*) remaps all files belonging to the old group and user id to match the new 
#     settings
# (*) executes /sbin/setuser USERNAME with rest of commandline params
#
# IMPORTANT NOTE: 
#
# This script calls usermod which changes files in the home directory with the 
# old uid AUTOMATICALLY to the new uid. Be aware that when you mount an external
# volume there and it matches the old uid (9999) this files will be changed!
#
# Lesson learned: NEVER ever use external mount points below $HOME
#
#-------------------------------------------------------------------------------
#
# The MIT License (MIT)
#
# Copyright (c) 2015 Tom Nussbaumer <thomas.nussbaumer@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################

if [ "$(id -u)" != "0" ]; then
   echo "[ERROR] $0 must be run as root" 1>&2
   exit 1
elif [ $# -lt 4 ]; then
   echo "[USAGE] $0 USERNAME NEW-UID NEW-GID command(s)" 1>&2
   exit 2
fi
export OLDUID=$(id -u "$1")
export OLDGID=$(id -g "$1")

#echo "remapuser: $OLDUID:$OLDGID -> $2:$3"

groupmod -g "$3" "$1"         >/dev/null 2>&1
usermod  -u "$2" -g "$3" "$1" >/dev/null 2>&1

## -xdev is important to prevent find from processing mounts
find / -xdev \( -uid "$OLDUID" -exec chown -h "$2" {} \; \) , \
             \( -gid "$OLDGID" -exec chgrp -h "$3" {} \; \)

GIVEN_UNAME="$1"
shift 3
exec setuser "$GIVEN_UNAME" "$@"
